---
# roles/helm/tasks/main.yml
- name: Check if Helm is already installed
  ansible.builtin.stat:
    path: "{{ helm_install_dir }}/helm"
  register: helm_binary

- name: Download Helm tarball
  ansible.builtin.get_url:
    url: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: "/tmp/helm-v{{ helm_version }}.tar.gz"
    mode: '0644'
  when: not helm_binary.stat.exists

- name: Extract Helm binary from archive
  ansible.builtin.unarchive:
    src: "/tmp/helm-v{{ helm_version }}.tar.gz"
    dest: "/tmp"
    remote_src: yes
    creates: "/tmp/linux-amd64/helm"
  when: not helm_binary.stat.exists

- name: Install Helm executable to {{ helm_install_dir }}
  ansible.builtin.copy:
    src: "/tmp/linux-amd64/helm"
    dest: "{{ helm_install_dir }}/helm"
    mode: '0755'
    remote_src: yes
  when: not helm_binary.stat.exists