- name: Check if node is already joined
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf_stat

- name: Fetch join command from master
  ansible.builtin.slurp:
    src: /tmp/kubeadm_join_cmd.sh
  delegate_to: "{{ groups['masters'][0] }}"
  register: join_cmd_content
  when: not kubelet_conf_stat.stat.exists

- name: Join the node to the cluster
  ansible.builtin.shell: "{{ join_cmd_content.content | b64decode | trim }}"
  when: not kubelet_conf_stat.stat.exists and join_cmd_content is defined