apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: pyramidnet-base

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app: pyramidnet-api
    version: v1.0.0

resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- hpa.yaml

images:
- name: pyramidnet-api
  newTag: v1.0.0
