- name: Log system information
  ansible.builtin.debug:
    msg:
      - "=== Node Information ==="
      - "Node: {{ inventory_hostname }}"
      - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
      - "Kernel: {{ ansible_kernel }}"
      - "Memory: {{ ansible_memtotal_mb }}MB"
      - "CPU: {{ ansible_processor_vcpus }} cores"
      - "Architecture: {{ ansible_architecture }}"
      - "========================"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-setuptools
      - python3-kubernetes
      - python3-yaml
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Disable swap
  ansible.builtin.mount:
    path: swap
    fstype: swap
    state: unmounted

- name: Remove swap entry from /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^\s*([^#]\S+\s+\S+\s+swap\s+)'
    state: absent

- name: Ensure required kernel modules are loaded
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - br_netfilter
    - overlay

- name: Ensure sysctl settings for Kubernetes networking
  ansible.builtin.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { key: 'net.bridge.bridge-nf-call-iptables', value: 1 }
    - { key: 'net.ipv4.ip_forward', value: 1 }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: 1 }


- name: Log package installation results
  ansible.builtin.debug:
    msg: "Installed packages: {{ apt_result.stdout_lines | default([]) }}"
  when: apt_result is defined and apt_result.changed