- name: Check if kubeadm has already run
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init_stat

- name: Initialize Kubernetes control plane
  ansible.builtin.command: kubeadm init --pod-network-cidr=192.168.0.0/16
  when: not kubeadm_init_stat.stat.exists
  register: kubeadm_init_result

- name: Create .kube directory for ubuntu user
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copy kubeconfig for ubuntu user
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: '0600'

- name: Generate kubeadm join command
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: join_command_result
  when: not kubeadm_init_stat.stat.exists or ansible_play_hosts | length > 1

- name: Save join command to file
  ansible.builtin.copy:
    content: "{{ join_command_result.stdout }}"
    dest: /tmp/kubeadm_join_cmd.sh
    mode: '0755'
  when: join_command_result is defined and join_command_result.stdout is defined

- name: Install Calico CNI
  ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  when: not kubeadm_init_stat.stat.exists
  register: calico_install

- name: Display Calico installation result
  ansible.builtin.debug:
    var: calico_install
  when: not kubeadm_init_stat.stat.exists

- name: Verify system pods are running
  ansible.builtin.shell: kubectl get pods -n kube-system
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  register: system_pods
  when: not kubeadm_init_stat.stat.exists

- name: Display system pods status
  ansible.builtin.debug:
    var: system_pods.stdout_lines
  when: not kubeadm_init_stat.stat.exists and system_pods is defined